go:
  command: >-
    go mod init {name}
  description: "Base golang console app"
  check: "go"
  mkdir: true
  justfile_path: "templates/go.justfile"
go-air:
  command: >-
    go mod init {name} &&
    air init"
  description: "Base golang console app with hot reload (require air installed)"
  check: "go air"
  mkdir: true
  justfile_path: "templates/go-air.justfile"
go-backend:
  command: >-
    go mod init {name} &&
    go get github.com/go-chi/chi/v5 &&
    go get github.com/mattn/go-sqlite3  &&
    air init"
  description: "Basic golang backend (chi,sqlc,dbmate,sqlite) app with hot reload (requires air,sqlc and dbmate installed)"
  check: "go air dbmate sqlc"
  mkdir: true
  justfile_path: "templates/go-air.justfile"
crystal:
  command: >-
    crystal init app {name}
  description: "Simple hello world program in Crystal"
  check: "crystal"
  mkdir: false
  justfile_path: "templates/crystal.justfile"

java-console:
  command: >-
    mvn archetype:generate -DgroupId=com.{name}.app -DartifactId={name}
    -DarchetypeArtifactId=maven-archetype-quickstart -DarchetypeVersion=1.5
    -DinteractiveMode=false
  description: "Simple hello world console application in Java"
  check: "mvn"
  mkdir: false
  justfile_path: "templates/java.justfile"

python:
  sources:
    "main.py": "templates/python/main.py"
  description: "Simple hello world program in Python"
  check: "python3"
  mkdir: true
  justfile_path: "templates/python.justfile"

csharp-console:
  command: >-
    dotnet new console -o {name} --use-program-main
  description: "Simple hello world console application in C#"
  check: "dotnet"

echo:
  command: >-
    echo {name}
  description: "Just echoes back the name"
  check: "echo"
