# name: Crystal CI

# on:
#   push:
#     branches: [ "master" ]
#   pull_request:
#     branches: [ "master" ]

# jobs:
#   build:

#     runs-on: ubuntu-latest

name: Build and Release
permissions:
  contents: write
  packages: write
on:
  push:
    tags:
      - '*'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal  
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install dependencies
        run: shards install
      
      # - name: Set up Just
      #   run: |
      #     curl -fsSL https://just.systems/install.sh | bash -s -- --to /usr/local/bin

      # - name: Build with Just
      #   run: just build

      - name: Build
        run: crystal build src/main.cr --release --cross-compile --static --link-flags -L/usr/lib -o build/soop
        
      - name: Archive built artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build/

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build/

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: true
      - name: Bundle assets
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r ./build/bundle.zip ./build/soop
      # - name: Bundle templates
      #   uses: montudor/action-zip@v1
      #   with:
      #     args: zip -qq -r ./templates.zip ./templates
      - name: Upload Bundle Asset
        id: upload-bundle-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./build/bundle.zip
          asset_name: soop-release-linux.zip
          asset_content_type: application/zip
      # - name: Upload Bundle Asset
      #   id: upload-template-asset 
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
      #     asset_path: ./templates.zip
      #     asset_name: templates.zip
      #     asset_content_type: application/zip
      # - name: Upload Bundle Asset
      #   id: upload-default-config 
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
      #     asset_path: ./config.yml
      #     asset_name: config.yml
      #     asset_content_type: application/yaml