# name: Crystal CI

# on:
#   push:
#     branches: [ "master" ]
#   pull_request:
#     branches: [ "master" ]

# jobs:
#   build:

#     runs-on: ubuntu-latest

#     container:
#       image: crystallang/crystal

#     steps:
#     - uses: actions/checkout@v4
#     - name: Install dependencies
#       run: shards install
#     - name: Run tests
#       run: crystal build
name: Build and Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Just
        run: |
          curl -fsSL https://just.systems/install.sh | bash -s -- --to /usr/local/bin

      - name: Build with Just
        run: just build

      - name: Archive built artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-${{ runner.os }}
          path: build/

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-*
          path: build/

      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          files: build/**/*
