# name: Crystal CI

# on:
#   push:
#     branches: [ "master" ]
#   pull_request:
#     branches: [ "master" ]

# jobs:
#   build:

#     runs-on: ubuntu-latest

name: Build and Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal  
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install dependencies
        run: shards install
      
      # - name: Set up Just
      #   run: |
      #     curl -fsSL https://just.systems/install.sh | bash -s -- --to /usr/local/bin

      # - name: Build with Just
      #   run: just build

      - name: Build
        run: crystal build src/main.cr --release --cross-compile --static --link-flags -L/usr/lib -o build/soop

      - name: Archive built artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build/

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-*
          path: build/

      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          files: 
            build/**/*
            templates/**/*
